name: Code Quality Check

on: [push]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace 'x' with the desired version
        
      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust if you have a different requirement file
        
      - name: Run Flake8
        run: |
          pip install flake8
          flake8 main.py
          
      - name: Run pylint
        run: |
          pip install pylint
          pylint main.py

